---
title: "Data modelling in R"
author: "Oterhia Samuel"
date: "2024-06-19"
output: html_document
---


```{r use the necessary libraries}
library(tidyverse)
library(readxl)
```

```{r import all files from addventureworks}

sales <- read_excel(file.choose())
products <- read_excel(file.choose())
region <- read_excel(file.choose())
calendar <- read_excel(file.choose())
customers <- read_excel(file.choose())

```

```{r show columns in each variable using view}
View(head(sales))
View(head(products))
View(head(region))
View(head(calendar))
View(head(customers))
```

```{r joining the sales and products table using the foreign key - prodkey}
sales_prod <- inner_join(x = sales, y = products, by = "prodkey")
```
```{r}
sales_cust <- inner_join(x = sales, y = customers, by = "custkey")
```
```{r}
view(head(sales_cust))
```

```{r}
sales_reg <- inner_join(x=sales, y=region, by="regionkey")
```
```{r}
View(head(sales_reg))
```

```{r}
sales_cal <- inner_join(x=sales, y = calendar, by="datekey")

```
```{r}
view(head(sales_cal))
```

```{r show total sales by category}
sales_prod %>% 
  group_by(category) %>% 
  summarise(total =format(x=  sum(revenue), big.mark =",", scientific=F))
 arrange(desc(total))
 
```
```{r}
sales_prod %>% 
  group_by(category) %>% 
  summarise(total = sum(revenue)) %>% 
 arrange(desc(total))
```
```{r}
sales_cal %>% 
  group_by(year) %>% 
  summarise(total_revenue = sum(revenue)) %>% 
  arrange(desc(total_revenue))
```
```{r}
sales_cal %>% 
  group_by(year) %>% 
  summarise(total_revenue = sum(revenue)) %>% 
  arrange(desc(total_revenue)) %>% 
  ggplot(aes(x=year, y=total_revenue)) +geom_col()
```

```{r}
sales_cust %>% 
  group_by(customer) %>% 
  summarise(total=sum(revenue)) %>% 
  arrange(desc(total)) %>% 
  head(5)
```
```{r}
sales_cal %>% 
  group_by(year) %>% 
  summarise(total =sum(revenue)) %>% 
  arrange(desc(total)) %>% 
  ggplot(aes(x=year, y=total, group=1)) +geom_line(aes(y=total), color = "red", size = 0.7) +
  geom_text(aes(x=year, y= total, label = total), vjust="inward", size=3)+
  scale_y_continuous(labels = scales::comma)
```

```{r}
sales_cal %>%
  filter(year==2019) %>%
  group_by(month) %>% 
  summarise(total =sum(revenue)) %>% 
  arrange(desc(total))
  
```

```{r}
sales_cal %>%
  filter(year==2019) %>%
  group_by(month) %>% 
  summarise(total =sum(revenue)) %>% 
  arrange(desc(total)) %>% 
   ggplot(aes(x=month, y=total,  group=1)) + geom_line(aes(y=total), color = "red", size = 0.7) +
  geom_text(aes(x=month, y= total, label = total), vjust= "inward", size=3)+
  scale_y_continuous(labels = scales::comma) 
```



